name: gopasal
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  food_with_love:
    git: https://github.com/shrijanRegmi/flutter-food-with-love.git
  always_scroll_list:
    git: https://github.com/shrijanRegmi/always_scroll_list.git
  google_fonts: ^2.1.0
  flutter_svg: ^1.0.0
  carousel_slider: ^4.0.0
  pin_code_fields: ^7.3.0
  shimmer:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/svgs/
